#!/bin/bash

COBALT_BIN_DIR=$(dirname $(test -L "$0" && readlink "$0" || echo "$0"))
PROJECT_ROOT_DIR=$(pwd)
PROJECT_CACHE_DIR=$(${COBALT_BIN_DIR}/getcachedir.sh ${PROJECT_ROOT_DIR})

function main {

    require make python

    case $1 in

        clean)
            clean
            ready
            ;;

        compile|package)
            requireCobaltProjectFileExists
            buildProjectCache
            build $1
            ready
            ;;

        # One of the build targets
        deploy)
            requireCobaltProjectFileExists
            buildProjectCache
            build .validatefingerprint 2>/dev/null \
                && clean \
                && build deploy
            ready
            ;;

        "--clear-cache")
            requireCobaltProjectFileExists
            clearCache
            ready
            ;;

        "--help")
            help
            ;;

        "--version")
            echo "Cobalt 1.0"
            ;;

        *)
            echo "ERROR: Invalid build target"
            exit 2
            ;;
    esac
}

function clean {
    echo "Deleting build directory"
    rm -fr "${PROJECT_ROOT_DIR}/target"
}

# Checks if the given dependencies are installed
function require {
    for program in $*; do
        command -v ${program} &>/dev/null
        if [ $? -ne 0 ]; then
            echo "ERROR: Missing required dependency: ${program}"
            exit 2
        fi
    done
}

# Checks if a Cobalt project file exists within the current directory. If it doesn't, then exit with exit code 2.
function requireCobaltProjectFileExists {
    # Check if the project root directory contains a Cobalt project file
    if [ ! -f "${PROJECT_ROOT_DIR}/cobalt.json" ]; then
        echo "ERROR: No Cobalt project file found in ${PROJECT_ROOT_DIR}"
        exit 2
    fi
}

# Build project cache, if necessary.
function buildProjectCache {
    export COBALT_BIN_DIR PROJECT_ROOT_DIR PROJECT_CACHE_DIR; make -s --directory "${PROJECT_ROOT_DIR}" -f "${COBALT_BIN_DIR}/project.makefile"
}

# Builds the build target (one of 'compile', 'deploy' or 'package').
function build {
    # Build the sources
    export COBALT_BIN_DIR; make -s -j --directory "${PROJECT_ROOT_DIR}" -f "${PROJECT_CACHE_DIR}/cobalt" $*
}

# Clears the project cache by deleting the project's cache directory.
function clearCache {
    echo "Clearing cache in ${PROJECT_CACHE_DIR}"
    rm -fr "${PROJECT_CACHE_DIR}"
}

# Prints 'Done' if the previous command was successful.
function ready {
    if [ $? -eq 0 ]; then
        echo "Done"
    fi
}

# Shows the help message.
function help {
    echo "Usage: cobalt [OPTIONS...] BUILDTARGET"
    echo "Runs the Cobalt build tool with the specified target"
    echo ""
    echo "OPTIONS:"
    echo "--clear-cache   Clear the cache of the current project"
    echo "--help          Show this help and exit"
    echo "--version       Show version and exit"
    echo ""
    echo "BUILDTARGET: Builds the specified target. Valid build targets are:"
    echo "  clean     Cleans up the project by removing the target directory"
    echo "  compile   Compiles all files"
    echo "  deploy    Cleans up the project, compiles all files and builds the package"
    echo "  package   Compiles all files and creates the package"
}

main $*
