#!/bin/bash

COBALT_BIN_DIR=$(dirname $(test -L "$0" && readlink "$0" || echo "$0"))
PROJECT_ROOT_DIR=$(pwd)
PROJECT_CACHE_DIR=$(${COBALT_BIN_DIR}/getcachedir.sh)

# Check if the project root directory contains a Cobalt project file
if [ ! -f "${PROJECT_ROOT_DIR}/cobalt.json" ]; then
    echo "ERROR: No Cobalt project file found in ${PROJECT_ROOT_DIR}"
    exit 2
fi

function main {

    case $1 in

        clean|compile|deploy|package)
            build $*
            local exitCode=$?
            if [ ${exitCode} -eq 0 ]; then
                echo "Done"
            fi
            exit ${exitCode}
            ;;

        "--help")
            help
            ;;

        *)
            echo "ERROR: Invalid build target"
            exit 2
            ;;
    esac
}

function build {

    # Build project cache, if necessary
    export COBALT_BIN_DIR PROJECT_ROOT_DIR PROJECT_CACHE_DIR; make -s --directory "${PROJECT_ROOT_DIR}" -f "${COBALT_BIN_DIR}/project.makefile"

    # Build the sources
    export COBALT_BIN_DIR; make -s --directory "${PROJECT_ROOT_DIR}" -f "${PROJECT_CACHE_DIR}/cobalt" $* 2>/dev/null
}

function help {
    echo "Usage: cobalt [OPTION...] BUILDTARGET"
    echo "Runs the Cobalt build tool with the specified target"
    echo ""
    echo "OPTIONS:"
    echo "--help   Show this help and exit"
    echo ""
    echo "BUILDTARGET: Builds the specified target. Valid build targets are:"
    echo "  clean     Cleans up the project by removing the target directory"
    echo "  compile   Compiles all files"
    echo "  deploy    Cleans up the project, compiles all files and builds the package"
    echo "  package   Compiles all files and creates the package"
}

main $*